# Generated by Django 4.2.23 on 2025-08-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0002_register_groups_register_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='alert_photos/'),
        ),
    ]
