# Generated by Django 4.2.23 on 2025-08-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe', '0004_location_alert_locarion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user_id',
        ),
    ]
